### ISSUE TITLE
miniMD [tools_minimd] case can not compile: with -mavx =sm_70

### ISSUE THREAD

**Issue by particleflow-dev** [kokkos/kokkos-tutorials#100]
> [tools_minimd]$ make
g++ -O3 -g  -I./MPI-Stubs -DKOKKOSP_ENABLE_PROFILING -DPRECISION=2 -I./ -I/home/dao/Kokkos/kokkos/core/src -I/home/dao/Kokkos/kokkos/containers/src -I/home/dao/Kokkos/kokkos/algorithms/src -I/home/dao/Kokkos/kokkos/tpls/desul/include -I/home/dao/Kokkos/kokkos/tpls/mdspan/include -std=c++17 **-mavx =sm_70** -fopenmp -I./ -I/home/dao/Kokkos/kokkos/core/src -I/home/dao/Kokkos/kokkos/containers/src -I/home/dao/Kokkos/kokkos/algorithms/src -I/home/dao/Kokkos/kokkos/tpls/desul/include -I/home/dao/Kokkos/kokkos/tpls/mdspan/include -c input.cpp
g++: warning: =sm_70: linker input file unused because linking not done
**g++: error: =sm_70: linker input file not found**: No such file or directory
make: *** [Makefile:124: input.o] Error 1

what is the option: -mavx =sm_70?

**Comment by masterleinad** [comment]
Are you using cmake? If not, I would recommend that over the Makefile since it doesn't assume a particular architecture.

**Comment by particleflow-dev** [comment]
Aha, thanks a lot. cmake did work. 
`
$ makedir build
$ cd build
$ cmake ..
$ make
`
