### ISSUE TITLE
Kokkos Tutorial 07/24/2018

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos-tutorials#12]
https://docs.google.com/spreadsheets/d/1MuSBl4Uh21tH2t4ENhvsVaS6p728fDmEjBiWyPAomvE/edit#gid=0

https://goo.gl/forms/BmAQtGBVnG28P5PJ2

**Comment by ibaned** [comment]
Please fill in your information in the spreadsheet (first link) and fill out the survey (second link)

**Comment by dsunder** [comment]
Users:
- go to google document ... 
- enter your name (and at your convenience fill out the questions)
- copy the ssh key and paste it into a file tutorial.pem, call "chmod 600 tutorial.pem" to set correct permissions
- copy ip address from the google document corresponding to your name
- log into the instance with "ssh -i tutorial.pem ec2-user@IPADDRESS"
- at first login the instance will clone kokkos, kokkos-tutorials, kokkos-kernels, kokkos-tools and a couple of small apps. 
- kokkos-tutorials can be found under: ${HOME}/Kokkos/kokkos-tutorials
