### ISSUE TITLE
Kokkos June Online Training

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos-tutorials#36]
# Due to a screw up on our side we need to postpone the training by a week to June 23th - June 25th 

The Kokkos team will provide a 3-day training consisting of Lectures and Hands-On exercises Tuesday June 23th through Thursday June 25th. If you plan to attend please send an email to celmont@sandia.gov so we get an idea of number of attendees.

## What is Kokkos?

Kokkos is a C++ Programming Model for Performance Portability developed by a team spanning some of the major HPC facilities in the world. It allows developers to implement their applications in a single source fashion, with hardware vendor agnostic programming patterns. Implemented as a C++ template meta programming library, Kokkos can be used with the primary tool chains on any HPC platforms. The model is used by many HPC applications both within and outside the US, and is the primary programming model for the efforts of the Sandia National Laboratory to make their engineering and science codes ready for exascale. At this point more than 100 projects are using Kokkos to obtain performance portability.

The tutorial will teach attendees the basics of Kokkos programming through a step-by-step sequence of lectures and hands-on exercises. Fundamental concerns of performance portable programming will be explained, and attendees will be provided with cloud instances to do the exercises on systems with GPUs and CPUs. At the end of the training, attendees will have learned how to dispatch parallel work with Kokkos, do parallel reductions, manage data, identify and manage data layout issues and expose hierarchical parallelism. The material used during the training will be available online, including the exercises and their solutions.

## Contents of the Tutorial
(Not necessarily in that order)

- Basic Kokkos Usage 
  - Data Management
  - Simple Kernels
- Basics of Performance Portable Programming for CPUs and GPUs 
  - Data access patterns
- Intermediate Kokkos Usage 
  - Complex Data structures
  - Scatter Contribute patterns
  - Basic Hierarchical Parallelism
- Advanced Kokkos Usage 
  - Advanced Hierarchical Parallelism (Vectorization and Scratch pads)
  - SIMD types
  - Task based programming.
- Kokkos Tools 
  - Profiling
  - Tuning
  - Debuggging
- GPU Performance Analysis
  - Kokkos Kernels Math Libraries

We will generally start 9am MT and go till 5pm MT with a longer break for lunch. Tuesday we will break from 11am to 1pm to allow summer students to attend a regular students event at 11 for them. 

## What do you need?

- You must be able to ssh to a linux system – we will provide AWS GPU instances
- Some C++ knowledge recommended
- Parallel programming experience helpful
- Sign up for the kokkosteam.slack.com channel if possible. Contact us if you can’t.

## Meeting Link

Will be posted here later.

We will use a ECP Zoom.gov account, ORNL is hosting the meeting.

**Comment by JoshuaSBrown** [comment]
Is the link going to be posted tomorrow morning?

**Comment by crtrott** [comment]
Should have posted this as a comment again: we screwed up unfortunately and had to postpone for a week. Very sorry for the inconvenience.

#Due to a screw up on our side we need to postpone the training by a week to June 23th - June 25th

**Comment by rviertel** [comment]
What is the correct meeting link to use? I got a Skype invite for the meeting but the above comment says it will be a zoom meeting.

**Comment by crtrott** [comment]
I think the link should include both?

**Comment by dalg24** [comment]
```
Exascale Computing Project - Zoom for Gov

Damien Lebrun-Grandie is inviting you to a scheduled ZoomGov meeting.

Topic: Kokkos June Online Training
Time: Jun 23, 2020 10:30 AM Eastern Time (US and Canada)

Join ZoomGov Meeting
https://exascaleproject.zoomgov.com/j/1611882302?pwd=MXRycE81N1RCS1lKK0FERHJuTjBPQT09

Meeting ID: 161 188 2302
Password: 627394
One tap mobile
+16692545252,,1611882302#,,#,627394# US (San Jose)
+16468287666,,1611882302#,,#,627394# US (New York)

Dial by your location
        +1 669 254 5252 US (San Jose)
        +1 646 828 7666 US (New York)
Meeting ID: 161 188 2302
Password: CONTACT_LEBRUNGRANDT_AT_ORNL_DOT_GOV_IF_YOU_DID_NOT_RECEIVE_THE_PASSWORD
Find your local number: https://exascaleproject.zoomgov.com/u/aew5SZHQFA

Join by Skype for Business
https://exascaleproject.zoomgov.com/skype/1611882302
```

**Comment by crtrott** [comment]
Note in the above the password is missing: CONTACT_LEBRUNGRANDT_AT_ORNL_DOT_GOV_IF_YOU_DID_NOT_RECEIVE_THE_PASSWORD

**Comment by rviertel** [comment]
Thanks!
